name: Check for Base Image Updates
on:
  push:
    branches:
      - master
      - image_update
jobs:
  check_update:    
    name: Check for Base Image Updates
    runs-on: ubuntu-latest
    outputs:
      rebuild: ${{ steps.compare.outputs.rebuild }}
    steps:
      - uses: actions/checkout@v2
      - name: run script
        run: |
          ./.github/check.sh
      - id: compare
        run: |
          echo $REBUILD
          echo "rebuild=$REBUILD" >> $GITHUB_OUTPUT
  
  call-workflow-passing-data:
    needs: check_update
    uses: ./.github/workflows/build_publish.yml
    with:
      rebuild: ${{ needs.check_update.outputs.rebuild }}
