name: Check for Base Image Updates
on:
  push:
    branches:
      - master
      - image_update
jobs:
  check_update:    
    name: Check for Base Image Updates
    runs-on: ubuntu-latest
    outputs:
      rebuild: ${{ steps.compare.outputs.rebuild }}
    steps:
      - uses: actions/checkout@v2
      - name: compare
        run: |
          ./.github/check.sh
          echo "::set-output name=rebuild::$REBUILD"
  
  call-workflow-passing-data:
    needs: check_update
    uses: ./.github/workflows/build_publish.yml
    with:
      rebuild: false #${{ needs.check_update.outputs.rebuild }}