name: Check for Base Image Updates
on:
  push:
    branches:
      - master
      - image_update

jobs:
  base-image-update-check:
    name: Check for Base Image Updates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Build and compare
        run: |
          ./.github/check.sh
          echo $REBUILD "Printing in same step"
      - name: checking variable
        run:  echo $REBUILD

